name: Build and upload zip installer to assets

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=$VERSION" >> $GITHUB_ENV
          sed -i "s/<version>/$VERSION/" .romm/__version__.py

      - name: Run build script
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh

      - name: Upload to GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: .dist/romm_muOS_install_${{ env.version }}.muxzip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
